# Generated by Django 4.2.2 on 2023-12-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
